# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the given branch
  push:
    branches: [ main ]
    paths: [ '**.php' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update source file translation strings
        id: update_pot
        run: |
          sudo apt-get install -y gettext
          xgettext --from-code=UTF-8 --add-comments='translators:' --keyword="pgettext:1c,2" -o php/i18n/litcal.pot php/index.php php/includes/enums/LitColor.php php/includes/enums/LitCommon.php php/includes/enums/LitGrade.php
          echo "::set-output name=POT_LINES_CHANGED::$(git diff -U0 | grep '^[+|-][^+|-]' | grep -Ev '^[+-]"POT-Creation-Date' | tee >(wc -l))"

      # push the output folder to your repo
      - name: Push changes
        if: ${{ steps.update_pot.outputs.POT_LINES_CHANGED > 0 }}
        uses: actions-x/commit@v4
        with:
          # The committer's email address
          email: 41898282+github-actions[bot]@users.noreply.github.com
          # The committer's name
          name: github-actions
          # The commit message
          message: regenerated i18n/litcal.pot from source files
          # The branch to push the changes back to, defaults to the current branch
          branch: ${{ github.ref }}
          # The files to add separated by space, defaults to every file
          files: php/i18n/litcal.pot
          # The repository to push the code to, defaults to origin (e.g. this repository)
          repository: origin
          # The token used to push the code, not needed if you push to the same repository
          #token: # default is ${{ github.token }}
          # Whether to perform force push
          force: 0
          # The working directory that will be used for git commands
          #directory: # default is .
