name: NodeJS with Gulp

on:
  push:
    branches: [ main ]
    paths: [ 'javascript/script.js' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Build
      run: |
        npm install --save-dev gulp i18next-scanner
        gulp --gulpfile 'gulpfile.js' i18next

    - name: Push changes  # push the output folder to your repo
      uses: actions-x/commit@v6
      with:
        # The committer's email address
        email: 41898282+github-actions[bot]@users.noreply.github.com
        # The committer's name
        name: github-actions
        # The commit message
        message: regenerated i18next translation.json files from source files
        # The branch to push the changes back to, defaults to the current branch
        branch: ${{ github.ref }}
        # The files to add separated by space, defaults to every file
        files: javascript/locales/**/translation.json
        # The repository to push the code to, defaults to origin (e.g. this repository)
        repository: origin
        # The token used to push the code, not needed if you push to the same repository
        #token: # default is ${{ github.token }}
        # Whether to perform force push
        force: 0
        # The working directory that will be used for git commands
        #directory: # default is .
